### ISSUE TITLE
提点小建议

### ISSUE THREAD

**Issue by my9988** [mtianyan/django-tyadmin#8]
搜到你这个项目和我要设计的项目接近，也是django restful api,本想借鉴复制你的组件，比如只复制一个User管理，我看几乎复制了半个项目了，组件化互相牵扯太多，建议所采用的组件和ant-design-pro接近，比如你用的mtianyan-pro-table，Pro-table有啥满足不了吗？还有excel导出组件，其实django后台就可以设计导出，你引用的组件万一不更新了呢，我的意思要跟主流。我也是才开始学习react相关的东西，感觉都到处封装，搞的人云山雾罩，说是react的优点在于组件化，但不是那么简单。

**Comment by mtianyan** [comment]
本项目是一个后端优先的代码生成器项目，你说借鉴一下希望拷一个用户管理，你是从哪个地方拷贝的呢，是demo_finish么？ 因为用户关联了权限，组，已经做了自动关联，所以从auto_page 里将user/group/permission三个文件夹一起拷走，或者你将其中的关联代码剔除，就只需要拷走user文件夹。

mtianyan-pro-table 就是pro-table稍加魔改，因为pro-table 官方不愿意更改统一样式提供表单多列布局等问题，以及后面pro-table 大版本升级正在剥离type=form 的表单创建，编辑，而转向推荐pro-form。这里我觉得没有必要跟进，因此留在了旧版本自己魔改。"@ant-design/pro-table": "2.4.4",

至于你说的excel导出，这里只是调用一个utils 里的导出方法传入一个json 数组。个人认为前端行为，不需要做额外工作，比django端搞更轻松愉快。

**Comment by mtianyan** [comment]
@my9988 欢迎加群304094780 讨论，反馈嘞，项目初期各种方向选型都还可以商量
