### ISSUE TITLE
关于Form布局的问题

### ISSUE THREAD

**Issue by my9988** [mtianyan/django-tyadmin#9]
我也请教过antd pro的chenshuai，他回复说antd支持layout,我没明白怎么用，我的问题是你的系统的CreateForm水平布局的，我也挺喜欢。但是我用V5布局显示如下：

![image](https://user-images.githubusercontent.com/17469220/102763630-f38e9180-439f-11eb-8463-807d261d770a.png)

        <ProForm.Group>
          <ProFormCheckbox name="is_superuser" label="is_superuser" labelAlign="left" />
          <ProFormCheckbox name="is_staff" label="is_staff" labelAlign="left" />
          <ProFormCheckbox name="is_active" label="is_active" labelAlign="left" />
        </ProForm.Group>
我也想实现这个CheckBox左右布局，labelAlign不生效，你肯定是高手，请问该怎么写呢？注意不是所有字段都左右，只有这个需要。

**Comment by mtianyan** [comment]
@my9988 抱歉哈，这个项目用的是旧版本的Protable，当时ProForm还不稳定，就没有使用。这个proForm 暂时没有去研究使用哈。
